[pymhf]
exe = "NMS.exe"
internal_mod_dir = "{CURR_DIR}/_internal_mods"
steam_gameid = 275850
start_paused = false
default_mod_save_dir = "{EXE_DIR}"

[pymhf.logging]
log_level = "info"
window_name_override = "NMS.py"
log_dir = "{EXE_DIR}"

[pymhf.gui]
shown = true
scale = 1
