name: NMSpy

on:
  # Run on all branches except for the gh-pages branch
  push:
    paths-ignore:
      - '*.md'
    branches-ignore:
      - 'gh-pages'
    tags:
      - '*'

jobs:
  build_test:
    name: Build artefacts
    runs-on: Windows-latest
    strategy:
      fail-fast: false
      matrix:
        py_ver: [{version: '3.9'}] # , {version: '3.10'}, {version: '3.11'}]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.py_ver.version}}
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.py_ver.version}}"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip uv
          uv sync --frozen --all-groups --all-extras
      - name: Build Python ${{ matrix.py_ver.version}} wheel
        run: uv build
      - name: Lint and format code
        run: |
          uv run ruff check ./nmspy
          uv run ruff format --check ./nmspy
          uv run python -m twine check ./dist/*
      - name: Upload Wheels
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
  release_check:
    name: Check whether to do a release
    needs:
      - build_test
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.whether_to_release.outputs.should_release}}
    permissions:
      id-token: write  # IMPORTANT: this permission is required to write to github envs
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check whether to release
        uses: MathieuMoalic/action-python-package-new-version@v1.0.5
      - name: Assign whether to release to output
        id: whether_to_release
        run: echo "should_release=${{ env.PUBLISHING }}" >> "$GITHUB_OUTPUT"
  release:
    name: Release NMSpy wheels and source build to PyPI
    # Only run this job if the commit was tagged.
    if: ${{ startsWith(github.ref, 'refs/tags') && needs.release_check.outputs.should_release == 'true' }}
    needs:
      - build_test
      - release_check
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/NMSpy
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Download files for release
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true

  test-release:
    name: Release NMSpy wheels and source build to test-PyPI
    # Only run this job if we merge into master. Addition check is added later.
    if: ${{ github.ref == 'refs/heads/master' && needs.release_check.outputs.should_release == 'true' }}
    needs:
      - build_test
      - release_check
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/NMSpy
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Download files for release
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          attestations: true
